FORMAT: 1A
HOST: http://localhost:4200/

# 页面路由 文档

该页面路由文档使用 API Blueprint 格式, 和Markdown类似.
文档内容包括 上游企业/核心企业/资金方/管理平台 的用户注册, 用户登陆, 用户中心页面路由




## Group 静态页面

金控系统的网站的静态页面


## 首页 [/web/index]

### 首页 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 企业金融 [/web/financing]

### 企业金融 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 安全保障 [/web/security]

### 安全保障 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 资金合作 [/web/cooperation]

### 资金合作 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 企业中心 [/web/enterprise]

### 企业中心 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }



## Group 上游企业用户

上游企业用户相关页面.


## 用户注册页面 [/web/upstream/register]

### 用户注册 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户登录页面 [/web/upstream/login]

### 用户登录 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户中心页面 [/web/upstream/index]

### 用户中心 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }




## Group 核心企业用户

核心企业用户相关页面.


## 用户注册页面 [/web/bridge/register]

### 用户注册 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户登录页面 [/web/bridge/login]

### 用户登录 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户中心页面 [/web/bridge/index]

### 用户中心 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }




## Group 资金方企业用户

资金方企业用户相关页面.


## 用户注册页面 [/web/capital/register]

### 用户注册 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户登录页面 [/web/capital/login]

### 用户登录 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户中心 [/web/capital/index]

### 用户中心 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }




## Group 平台管理

平台管理用户相关页面.


## 用户登录页面 [/web/platform/login]

### 用户登录 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }


## 用户中心页面 [/web/platform/index]

### 用户中心 [GET]

+ Response 200 (text/html)

        {
            "success": true,
            "data": "页面"
        }
